c

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,21 +31,43 @@ jobs:
         run: sbt clean assembly
 
       - name: Authenticate with GCP
+        uses: google-github-actions/auth@v1
+        with:
+          credentials_json: ${{ secrets.GCP_SA_KEY }}
+
+      - name: Verify Authentication
         run: |
-          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-key.json
-          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV
+          echo "Authenticated accounts:"
+          gcloud auth list
+          echo "Active account:"
+          gcloud config get-value account
+          echo "Google Application Credentials:"
+          echo $GOOGLE_APPLICATION_CREDENTIALS
+
+      - name: Check GCS Access
+        run: |
+          echo "Checking GCS access:"
+          gsutil ls gs://github-act
 
       - name: List files in DAGs directory
-        run: ls -alh $GITHUB_WORKSPACE/dags/
+        run: |
+          echo "Listing files in DAGs directory:"
+          ls -alh $GITHUB_WORKSPACE/dags/
 
       - name: Upload DAG to GCP Bucket
-        run: gsutil cp $GITHUB_WORKSPACE/dags/hello_world_dag.py gs://github-act/dags/
+        run: |
+          echo "Attempting to upload DAG:"
+          gsutil cp $GITHUB_WORKSPACE/dags/hello_world_dag.py gs://github-act/dags/
 
       - name: Check if JAR file exists
-        run: ls -alh $GITHUB_WORKSPACE/target/scala-2.13/ || echo "JAR directory not found"
+        run: |
+          echo "Checking if JAR file exists:"
+          ls -alh $GITHUB_WORKSPACE/target/scala-2.13/ || echo "JAR directory not found"
 
       - name: Upload JAR to GCP Bucket
-        run: gsutil cp $GITHUB_WORKSPACE/target/scala-2.13/*.jar gs://github-act/jars/
+        run: |
+          echo "Attempting to upload JAR file:"
+          gsutil cp $GITHUB_WORKSPACE/target/scala-2.13/*.jar gs://github-act/jars/
         if: success()
 
       - name: Trigger Airflow DAG Run (Optional)
@@ -54,6 +76,7 @@ jobs:
           AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
           AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
         run: |
+          echo "Triggering Airflow DAG Run:"
           curl -X POST "$AIRFLOW_URL/api/v1/dags/hello_world_dag/dagRuns" \
           -H "Content-Type: application/json" \
           --user "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
