e

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,18 +31,22 @@ jobs:
         run: sbt clean assembly
 
       - name: Authenticate with GCP
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SA_KEY }}
+        run: |
+          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-key.json
+          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV
 
-      - name: List files in dags directory
+      - name: List files in DAGs directory
         run: ls -alh $GITHUB_WORKSPACE/dags/
 
       - name: Upload DAG to GCP Bucket
         run: gsutil cp $GITHUB_WORKSPACE/dags/hello_world_dag.py gs://github-act/dags/
 
+      - name: Check if JAR file exists
+        run: ls -alh $GITHUB_WORKSPACE/target/scala-2.13/ || echo "JAR directory not found"
+
       - name: Upload JAR to GCP Bucket
         run: gsutil cp $GITHUB_WORKSPACE/target/scala-2.13/*.jar gs://github-act/jars/
+        if: success()
 
       - name: Trigger Airflow DAG Run (Optional)
         env:
